### ISSUE TITLE
Coding style section - Commenting Tags - Example

### ISSUE THREAD

**Issue by rcbirsan** [insum-labs/plsql-and-sql-coding-guidelines#4]
For the last example in the Coding style section - https://github.com/insum-labs/plsql-and-sql-coding-guidelines/blob/master/docs/3-coding-style/coding-style.md, I suggest to use the javadoc format/template supported by these 3(three) references:
- https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html 
- https://plsql-md-doc.readthedocs.io/en/latest/javadoc-template/
- https://www.thatjeffsmith.com/archive/2012/03/javadoc-for-the-database-a-la-dbdoc-via-sql-developer/

Also, the SQL statement has inconsistent formatting (upper and lower case, end of statement present for one example and missing another one).

**Comment by rimblas** [comment]
Yes, absolutely.  Comments will be JavaDoc style.  Will amend.
